Solved lower SDK version error in LPT.
In lower sdk;s there is no option for asking for background location permission, in code there was an todo task which was giving error on runtime.

Removing it will solve the error and in lower sdks backgorund access will be shown as ‘no’ in the UI.

Files Included : Location privacy config Activity (line 92 - 103)

Error log :

`Process: org.envirocar.app, PID: 18845
kotlin.NotImplementedError: An operation is not implemented: VERSION.SDK_INT < Q
at de.fh.muenster.locationprivacytoolkit.ui.LocationPrivacyConfigActivity.onCreate(LocationPrivacyConfigActivity.kt:95)`